---
#- name: Create Vagrantfile
#  debug: msg="Variable lesson {{ lesson }} and year {{ year }}"

- name: Generate Vagrantfile for {{lesson.name}}
  template:
    dest: "{{year}}/{{lesson.name}}"
    src: Vagrantfile

- name: Generate synced_folders
  file:
    path: "{{year}}/{{lesson.name}}/{{item.host}}"
    state: directory
  with_items:
    - "{{lesson.synced_folders|default([])}}"
  when: lesson.synced_folders is defined

- name: Clone git repositories
  git:
    dest: "{{year}}/{{lesson.name}}/{{item.0.host}}/{{item.1.dest}"
    repo: "{{item.1.repo}}"
  with_subelements:
  - "{{lesson.synced_folders|default([])}}"
  - git
  when: lesson.synced_folders is defined
