---
- name: Debug Vagrantfile
  debug: msg="Variable lesson {{ lesson }} and year {{ year }}"

- name: Generate Vagrantfile for {{lesson.name}}
  template:
    dest: "{{year}}/{{lesson.name}}"
    src: Vagrantfile

- name: Generate synced_folders
  file:
    path: "{{year}}/{{lesson.name}}/{{item.1.host}}"
    state: directory
  with_subelements:
    - "{{lesson.pcs|default([])}}"
    - synced_folders
    - flags:
      skip_missing: true
  when: item.1 is defined

- include: git.yml
  vars:
    folder: "{{year}}/{{lesson.name}}/{{item.1.host}}"
    git: "{{item.1.git}}"
  with_subelements:
    - "{{lesson.pcs|default([])}}"
    - synced_folders
    - flags:
      skip_missing: true
  loop_control:
    loop_var: git_item
  when: item.1.git is defined
